### ISSUE TITLE
Throwing an error: ERROR TypeError: Cannot read property component of undefined

### ISSUE THREAD

**Issue by SergeySagan** [Bogdan1975/ng2-styled-directive#1]
I am using ng2 (v4), in fact here is my package.json:

`"dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4",
    "ng2-slideable-directive": "^1.0.13",
    "ng2-styled-directive": "^1.0.5"
  },
  "devDependencies": {
    "@angular/cli": "1.0.6",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }`

I am trying to use this package in https://github.com/Bogdan1975/ng2-slider-component
My project uses Angular CLI. I get this error whether I `npm` in the `ng2-slider-component` or download the source and copy the source files directly into my project. However, for this situation I copied the source into my project and when I remove all references to `ng2-styled-directive` from `ng2-slider-component` (including the html), I got the project to build and run perfectly, though the slider needs to have some styling done to get it to work.

Otherwise, I get this nasty error:

> Ng2SliderComponent.ngfactory.js:199 ERROR TypeError: Cannot read property 'component' of undefined at Ng2StyledDirective.ngAfterViewInit (vendor.bundle.js:24206) at callProviderLifecycles (vendor.bundle.js:12979) at callElementProvidersLifecycles (vendor.bundle.js:12954) at callLifecycleHooksChildrenFirst (vendor.bundle.js:12938) at checkAndUpdateView (vendor.bundle.js:14043) at callViewAction (vendor.bundle.js:14400) at execComponentViewsAction (vendor.bundle.js:14332) at checkAndUpdateView (vendor.bundle.js:14041) at callViewAction (vendor.bundle.js:14400) at execComponentViewsAction (vendor.bundle.js:14332)

Hopefully someone has some clues as to what is going on.

**Comment by neoswf** [comment]
Have been fixed in this PR: https://github.com/Bogdan1975/ng2-styled-directive/pull/2.
@Bogdan1975 - Please approve 👍
